version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/admin?ssl=false

  pubsub:
    build:
      context: ./pubsub
      dockerfile: pubsub.dockerfile
    environment:
      PUBSUB_PROJECT1: recon-bank,movements:user:monitor
    ports:
      - "8681:8681"

  publisher-api:
    build:
      context: ./publisher_api
      dockerfile: publisher_api.dockerfile
    environment:
      PUBLISHER_API_PORT: 5000
      PUBSUB_EMULATOR_HOST: pubsub:8681
      PUBSUB_PROJECT_ID: recon-bank
      PUBSUB_TOPIC_ID: movements
      MONGO_PROTOCOL: mongodb
      MONGO_HOST: mongo:27017
      MONGO_USER: admin
      MONGO_PASSWORD: pass
      MONGO_DBNAME: admin
    ports:
      - "5000:5000"
    depends_on:
      - pubsub
      - mongo

  front-user:
    build:
      context: .
      dockerfile: front_user.dockerfile
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8681
      PubSub__ProjectId: recon-bank
      PubSub__SubscriptionId: user
      PublisherApi__Address: http://publisher-api:5000
    ports:
      - "5001:5001"
    depends_on:
      - pubsub
      - publisher-api
